Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KillerAppSE2.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult About()
        {
            return View();
        }
    }
}

Controllers/OuderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KillerAppSE2.Controllers
{
    public class OuderController : Controller
    {
        // GET: Ouder
        public ActionResult OuderBase()
        {
            return View();
        }
    }
}

Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KillerAppSE2.Connector;
using KillerAppSE2.Context;
using KillerAppSE2.Models;
using KillerAppSE2.Repository;

namespace KillerAppSE2.Controllers
{
    public class RegisterController : Controller
    {
        public UserRepository UserRepository = new UserRepository(new SQLContextUser(new MSSQLConnector()));
        public Ouder ouder { get; private set; }

        // GET: Register
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Ouder()
        {
            return View();
        }

        public ActionResult Student()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterOuder(string initialen, string achternaam, int loginPin, string email, string telNr, string mobNr, string thuisAdres, int leeftijd)
        {
            Ouder ouder = new Ouder(initialen, achternaam, loginPin, email, telNr, mobNr, thuisAdres, leeftijd);

            if (UserRepository.UserRegister(ouder))
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                Response.Write("<script>alert('Registreren mislukt, probeer opnieuw');</script>");
                return View("Ouder");
            }

        }

        [HttpPost]
        public ActionResult RegisterStudent(string initialen, string achternaam, int loginPin, string email, string telNr, string thuisAdres, string StudLocatie)
        {
            Student student = new Student(initialen, achternaam, loginPin, email, telNr, thuisAdres, StudLocatie);

            if (UserRepository.UserRegister(student))
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                Response.Write("<script>alert('Registreren mislukt, probeer opnieuw');</script>");
                return View("Student");
            }

        } 

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - StuMobiel</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.intellisense.js"></script>
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Stumobiel", "Index", "Login", null , new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Over StuMobiel", "About", "About", null, new { @class = "navbar-brand"})</li>
                    <li>@Html.ActionLink("Registreren", "Register", "Register", null, new { @class = "navbar-brand" })</li>
                    </ul>
                </div>
            </div>
        </div>
<br/>
<br/>
<br/>
<br/>

    

<div class="container body-content">
            @RenderBody()
            <hr />

            <footer>
                <p>&copy; @DateTime.Now.Year - StuMobiel</p>
            </footer>
        </div>
    

</body>
</html>

Views/Shared/_LayoutLoggedInOuder.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - StuMobiel</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.intellisense.js"></script>
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Stumobiel", "OuderBase", "Ouder", null , new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Uitloggen", "Index", "Login", null, new { @class = "navbar-brand" })</li>
                    </ul>
                </div>
            </div>
        </div>
<br/>
<br/>
<br/>
<br/>

    

<div class="container body-content">
            @RenderBody()
            <hr />

            <footer>
                <p>&copy; @DateTime.Now.Year - StuMobiel</p>
            </footer>
        </div>
    

</body>
</html>

Views/Shared/_LayoutLoggedInStudent.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - StuMobiel</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.intellisense.js"></script>
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Stumobiel", "StudentBase", "Student", null , new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Beschikbaarheid", "Beschikbaarheid", "Student", null, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Uitloggen", "Index", "Login", null, new {@class = "navbar-brand"})</li>
                    </ul>
                </div>
            </div>
        </div>
<br/>
<br/>
<br/>
<br/>

    

<div class="container body-content">
            @RenderBody()
            <hr />

            <footer>
                <p>&copy; @DateTime.Now.Year - StuMobiel</p>
            </footer>
        </div>
    

</body>
</html>